FROM python:3.11.8

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN python -m spacy download en_core_web_sm

COPY ./app /code/app

CMD [ "uvicorn", "app.api:app", "--host", "0.0.0.0","--port","8000" ]